# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - label: "Trigger Auditbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - auditbeat/
                - .buildkite/auditbeat/
                - .buildkite/scripts
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/**
                - testing/**
              config:
                trigger: "auditbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Triggering Build for Auditbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "false"
    trigger: "auditbeat"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
        - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
        - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Heartbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - heartbeat/
                - .buildkite/heartbeat/
                - .buildkite/scripts
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/**
                - testing/**
              config:
                trigger: "heartbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Filebeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - filebeat/
                - .buildkite/filebeat/
                # CI related scripts
                - .buildkite/scripts
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools
                - libbeat/**
                - testing/**
              config:
                trigger: "filebeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger x-pack/filebeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/filebeat/
                - x-pack/libbeat/
                - .buildkite/x-pack/pipeline.xpack.filebeat.yml
                - .buildkite/scripts
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/**
                - testing/**
              config:
                trigger: "beats-xpack-filebeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Xpack/Dockerlogbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/dockerlogbeat/
                - .buildkite/x-pack/pipeline.xpack.dockerlogbeat.yml
                - .buildkite/hooks/
                - .buildkite/scripts
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/**
                - testing/**
              config:
                trigger: "beats-xpack-dockerlogbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Metricbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - metricbeat/
                - .buildkite/metricbeat/
                - .buildkite/scripts
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/**
                - testing/**
              config:
                trigger: "beats-metricbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger x-pack/metricbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/metricbeat/
                - x-pack/libbeat/common/aws
                - .buildkite/x-pack/pipeline.xpack.metricbeat.yml
                - .buildkite/scripts
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/**
                - testing/**
              config:
                trigger: "beats-xpack-metricbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger x-pack/osquerybeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/osquerybeat/**
                - .buildkite/x-pack/pipeline.xpack.metricbeat.yml
                - .buildkite/scripts/**
                - .buildkite/hooks/**
                # x-pack
                - libbeat/**
                - x-pack/libbeat/**
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/**
                - testing/**
              config:
                trigger: "beats-xpack-osquerybeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Xpack/Winlogbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/winlogbeat/
                - .buildkite/x-pack/pipeline.xpack.winlogbeat.yml
                - .buildkite/scripts
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/**
                - libbeat/**
                - testing/**
              config:
                trigger: "beats-xpack-winlogbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Deploy/K8S"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - .buildkite/deploy/kubernetes/**
                - .buildkite/hooks/
                - .buildkite/scripts
                - deploy/kubernetes/**
                - libbeat/docs/version.asciidoc
              config:
                trigger: "deploy-k8s"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Libbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - libbeat/
                - .buildkite/libbeat/pipeline.libbeat.yml
                - .buildkite/scripts
                - .buildkite/hooks
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - testing/
              config:
                trigger: "beats-libbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger x-pack/libbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/libbeat/
                - .buildkite/x-pack/pipeline.xpack.libbeat.yml
                - .buildkite/scripts
                - .buildkite/hooks
                # x-pack
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/
                - testing/
              config:
                trigger: "beats-xpack-libbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger x-pack/auditbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/auditbeat/
                - .buildkite/x-pack/pipeline.xpack.auditbeat.yml
                - .buildkite/scripts/
                - .buildkite/hooks/
                # x-pack
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/
                - testing/
                - x-pack/libbeat/
              config:
                trigger: "beats-xpack-auditbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger x-pack/heartbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/heartbeat/
                - .buildkite/x-pack/pipeline.xpack.heartbeat.yml
                - .buildkite/scripts/
                - .buildkite/hooks/
                # x-pack
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/
                - testing/
                - x-pack/libbeat/
              config:
                trigger: "beats-xpack-heartbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger x-pack/packetbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - x-pack/packetbeat/
                - .buildkite/x-pack/pipeline.xpack.packetbeat.yml
                - .buildkite/scripts/
                - .buildkite/hooks/
                # x-pack
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/
                - testing/
                - x-pack/libbeat/
              config:
                trigger: "beats-xpack-packetbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Winlogbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - winlogbeat/
                - .buildkite/winlogbeat/pipeline.winlogbeat.yml
                - .buildkite/scripts
                - .buildkite/hooks
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/
                - testing/
              config:
                trigger: "beats-winlogbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}

  - label: "Trigger Packetbeat"
    if: build.env("BUILDKITE_PULL_REQUEST") == "true"
    plugins:
      - monorepo-diff#v1.0.1:
          diff: "git diff --name-only origin/${GITHUB_PR_TARGET_BRANCH}...HEAD"
          watch:
            - path:
                - packetbeat/
                - .buildkite/packetbeat/pipeline.packetbeat.yml
                - .buildkite/scripts/
                - .buildkite/hooks/
                #OSS
                - go.mod
                - pytest.ini
                - dev-tools/
                - libbeat/
                - testing/
              config:
                trigger: "beats-packetbeat"
                build:
                  commit: "${BUILDKITE_COMMIT}"
                  branch: "${BUILDKITE_BRANCH}"
                  env:
                    - BUILDKITE_PULL_REQUEST=${BUILDKITE_PULL_REQUEST}
                    - BUILDKITE_PULL_REQUEST_BASE_BRANCH=${BUILDKITE_PULL_REQUEST_BASE_BRANCH}
                    - GITHUB_PR_LABELS=${GITHUB_PR_LABELS}
