when:
    changeset: ## when PR contains any of those entries in the changeset
        - "auditbeat/**"
        - "@ci" ## special token regarding the changeset for the ci
        - "@oss" ## special token regarding the changeset for the oss
stages:
    # mandatory stage - it runs always for:
    #   - branches/tags
    #   - on PRs
    #   - GitHub comment /test auditbeat
    #   - GitHub label auditbeat
    mandatory:
        # NOTE: stage name should be unique!
        unitTest:
            command: "mage auditbeat build unitTest"
            platform: "family/platform-ingest-beats-ubuntu-2204"
        crosscompile:
            command: "make -C auditbeat crosscompile"
            platform: "family/platform-ingest-beats-ubuntu-2204"
        unitTest-rhel-9:
            command: "mage auditbeat build unitTest"
            platform: "family/platform-ingest-beats-rhel-9"
        unitTest-windows-2022:
            command: "mage build unitTest"
            platform: "family/platform-ingest-beats-windows-2022"
        unitTest-windows-2016:
            command: "mage build unitTest"
            platform: "family/platform-ingest-beats-windows-2016"
    # optional stage - it runs on:
    #   - branches/tags
    #   - on PRs if:
    #       - GitHub comment /test auditbeat <sub-stage-name> . i.e: /test auditbeat integTest
    #       - GitHub label <sub-stage-name> . i.e: integTest or unitTest-arm or unitTest-macos ...
    extended:
        # NOTE: stage name should be unique!
        integTest:
            command: ".buildkite/auditbeat/scripts/integ-test.sh"
            platform: "platform-ingest-beats-ubuntu-2204-aarch64"
            provider: "aws"
        integTest-arm:
            command: ".buildkite/auditbeat/scripts/integ-test.sh"
            platform: "platform-ingest-beats-ubuntu-2204-aarch64"
            provider: "aws"
        unitTest-arm:
            command: ".buildkite/auditbeat/scripts/unit-tests.sh"
            platform: "platform-ingest-beats-ubuntu-2204-aarch64"
            provider: "aws"
        unitTest-macos:
            command: ".buildkite/auditbeat/scripts/unit-tests.sh"
            platform: "generic-13-ventura-x64"
            provider: "orka"
        unitTest-windows-2019:
            command: ".buildkite/auditbeat/scripts/unit-tests-win.ps1"
            platform: "family/core-windows-2019"
