# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
name: "beats-xpack-filebeat"

env:
  AWS_ARM_INSTANCE_TYPE: "t4g.xlarge"

  GCP_DEFAULT_MACHINE_TYPE: "c2d-highcpu-8"
  GCP_HI_PERF_MACHINE_TYPE: "c2d-highcpu-16"
  GCP_WIN_MACHINE_TYPE: "n2-standard-8"

  IMAGE_MACOS_ARM: "generic-13-ventura-arm"
  IMAGE_MACOS_X86_64: "generic-13-ventura-x64"
  IMAGE_UBUNTU_ARM_64: "platform-ingest-beats-ubuntu-2204-aarch64"
  IMAGE_UBUNTU_X86_64: "family/platform-ingest-beats-ubuntu-2204"
  IMAGE_WIN_10: "family/platform-ingest-beats-windows-10"
  IMAGE_WIN_11: "family/platform-ingest-beats-windows-11"
  IMAGE_WIN_2016: "family/platform-ingest-beats-windows-2016"
  IMAGE_WIN_2019: "family/platform-ingest-beats-windows-2019"
  IMAGE_WIN_2022: "family/platform-ingest-beats-windows-2022"

  # Other deps
  ASDF_MAGE_VERSION: 1.15.0

steps:
  - group: "x-pack/filebeat Mandatory Tests"
    key: "x-pack-filebeat-mandatory-tests"
    steps:
      - label: ":linux: Ubuntu Unit Tests"
        key: "x-pack-filebeat-mandatory-linux-unit-test"
        command: |
          cd x-pack/filebeat
          mage build unitTest
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
        artifact_paths:
          - "x-pack/filebeat/build/*.xml"
          - "x-pack/filebeat/build/*.json"
        notify:
          - github_commit_status:
              context: "x-pack/filebeat: Ubuntu Unit Tests"

      - label: ":go: Go (MODULE) Integration Tests"
        key: "x-pack-filebeat-mandatory-int-test"
        command: |
          set -euo pipefail
          # defines the MODULE env var based on what's changed in a PR
          source .buildkite/scripts/changesets.sh
          defineModuleFromTheChangeSet x-pack/filebeat
          echo "~~~ Will run tests with env var MODULE=$$MODULE"
          cd x-pack/filebeat && mage goIntegTest
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
        artifact_paths:
          - "x-pack/filebeat/build/*.xml"
          - "x-pack/filebeat/build/*.json"
        notify:
          - github_commit_status:
              context: "x-pack/filebeat: Go (MODULE) Integration Tests"

      - label: ":python: Python (MODULE) Integration Tests"
        key: "x-pack-filebeat-mandatory-python-int-test"
        command: |
          set -euo pipefail
          # defines the MODULE env var based on what's changed in a PR
          source .buildkite/scripts/changesets.sh
          defineModuleFromTheChangeSet x-pack/filebeat
          echo "~~~ Running tests with env var MODULE=$$MODULE"
          cd x-pack/filebeat && mage pythonIntegTest
        agents:
          provider: "gcp"
          image: "${IMAGE_UBUNTU_X86_64}"
          machineType: "${GCP_DEFAULT_MACHINE_TYPE}"
        artifact_paths:
          - "x-pack/filebeat/build/*.xml"
          - "x-pack/filebeat/build/*.json"
        notify:
          - github_commit_status:
              context: "x-pack/filebeat: Python (MODULE) Integration Tests"
